### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by WolfspiritM** [Neopallium/openjp2#2]
Hi. Thanks for that port!

Will it be possible to get this running for windows, too?
Currently it doesn't seem to compile on windows cause of:

```
error[E0432]: unresolved imports `libc::fseeko`, `libc::ftello`
  --> (...)\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openjp2-0.4.1\src\openjpeg.rs:46:36
   |
46 | use ::libc::{fclose, fopen, fread, fseeko, ftello, fwrite, FILE};
   |                                    ^^^^^^  ^^^^^^ no `ftello` in the root
   |                                    |
   |                                    no `fseeko` in the root
   |
help: a similar name exists in the module
   |
46 | use ::libc::{fclose, fopen, fread, fseek, ftello, fwrite, FILE};
   |                                    ~~~~~
help: a similar name exists in the module
   |
46 | use ::libc::{fclose, fopen, fread, fseeko, ftell, fwrite, FILE};
```

And without "file-io" I get:
```
error: linking with `link.exe` failed: exit code: 1120
  | ...
note:    Creating library (...)\deps\openjp2-9199e30fe6120138.dll.lib and object (...)\deps\openjp2-9199e30fe6120138.dll.exp
          openjp2-9199e30fe6120138.openjp2.c92809d76edc7b4c-cgu.12.rcgu.o : error LNK2019: unresolved external symbol posix_memalign referenced in function _ZN7openjp26malloc19opj_aligned_alloc_n17h660b3c5df47d8a53E
          (...)\deps\openjp2-9199e30fe6120138.dll : fatal error LNK1120: 1 unresolved externals
```

**Comment by Neopallium** [comment]
The first issue should already be fixed in the latest code, I replaces almost all usages of the `libc::FILE` with safe Rust code.  Only the dump API takes a `FILE` reference, but it only needs `fprintf` right now.

I will take a look at the second issue, I think it should be easy to fix.

**Comment by Neopallium** [comment]
Just published version `0.5.0` with fixed support for Windows and MacOS. Add both platforms to the CI too. Also published a new version `0.7.0` of `jpeg2k` to pull in this release.

Let me know if you still have compile issues.

**Comment by WolfspiritM** [comment]
Thank you for the quick response!

It does compile now however when decoding a simple image like https://github.com/Neopallium/jpeg2k/raw/main/samples/Hadley_Crater_provides_deep_insight_into_martian_geology_(7942261196).jp2 I get an error.

```
...
[2024-04-20T10:52:52Z DEBUG openjp2::t2] included=0
[2024-04-20T10:52:52Z DEBUG openjp2::t2] included=0
[2024-04-20T10:52:52Z DEBUG openjp2::t2] included=0
[2024-04-20T10:52:52Z DEBUG openjp2::t2] hdrlen=131
[2024-04-20T10:52:52Z DEBUG openjp2::t2] packet body
error: process didn't exit successfully: `test.exe` (exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)
```

**Comment by Neopallium** [comment]
What program are you using for the test?  Also what features did you use to compile it?

Also try doing a debug build instead of a release build, maybe it will provide more details about where it crashed.

I can't reproduce on Linux using the `convert_jp2` example.

**Comment by WolfspiritM** [comment]
I did use a debug build. There is no more information sadly.

Cargo.toml:
```toml
[package]
name = "openjp-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.12.4"
image = { version = "^0.24" }
env_logger = "0.11"
jpeg2k = { version = "0.7", default-features = false, features = ["image", "threads", "openjp2"]}
```

main.rs:
```rs
#[tokio::main]
async fn main() {
    std::env::set_var("RUST_LOG", "debug");
    env_logger::init();

    let url = "https://github.com/Neopallium/jpeg2k/raw/main/samples/Hadley_Crater_provides_deep_insight_into_martian_geology_(7942261196).jp2";
    let bytes = reqwest::get(url).await.unwrap().bytes().await.unwrap();
    
    let jp2_image = jpeg2k::Image::from_bytes(&bytes).unwrap();
    let image: image::DynamicImage = (&jp2_image).try_into().unwrap();

    image.save("output.jpg").unwrap();
}
```

Results in ```error: process didn't exit successfully: `target\debug\openjp-test.exe` (exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)```

Switching to openjpeg-sys in Cargo.toml works fine.

I just tried to run the same sample in WSL/Linux and it works fine. Seems to be related to Windows.

**Comment by Neopallium** [comment]
Maybe the `posix_memalign` fix for windows is wrong, it required a different "aligned" allocation function for windows.

**Comment by Neopallium** [comment]
Might have fixed it.  Please update to `0.5.1` and try that on windows.  On windows aligned allocations have special `realloc` and `free` functions.

`cargo update -p openjp2`

**Comment by WolfspiritM** [comment]
```
error[E0061]: this function takes 2 arguments but 3 arguments were supplied
   |
97  |     r_ptr = libc::aligned_malloc(ptr, new_size, alignment)
    |             ^^^^^^^^^^^^^^^^^^^^ -----
    |                                  |
    |                                  unexpected argument of type `*mut c_void`
    |                                  help: remove the extra argument
    |
```

However I manually removed "ptr, " in the cargo cache and recompiled and now it works!
Thank you very much!

**Comment by Neopallium** [comment]
I should have pushed the change and let the CI run.  Pushing a fix now and will publish a new version when it runs ok.

**Comment by Neopallium** [comment]
Version `0.5.2` has been published.

**Comment by WolfspiritM** [comment]
That works! Thanks!
